"""Normalize row-dict key sets before writing.

Different scenario generators (and the base estate rows an "augment" run
tags) do not all attach exactly the same set of provenance columns to
every row -- for example, a Member row generated only as a supporting
fixture for `duplicate_claims` is tagged `data_provenance`/
`synthetic_batch_id` but no `scenario_type` (it isn't itself the thing
being tested), while a Member row generated by `normal_claims` gets all
three (see `scenarios.py`). Once rows from several generators are merged
into the same `RawEstate` list, that key-set mismatch becomes a real bug
for exactly one of `data_plane.subsetting.writer`'s five writers:
`write_pbm_extract` derives its CSV header from ``rows[0].keys()`` alone
(see its own module docstring for why -- it mirrors the original
`writers/adls_writer.py`'s behavior), so a later row with a key the first
row lacks raises `csv.DictWriter`'s "dict contains fields not in
fieldnames". (The other four writers -- SQLite via `pandas.to_sql`,
Parquet via `DataFrame.to_parquet`, and NDJSON via one independent
`json.dumps` per line -- all tolerate heterogeneous keys natively, so
this module's fix targets the one writer that does not, but is applied
uniformly for safety.)

Reused, not reinvented: rather than special-case `write_pbm_extract` or
change Phase 4's writer, this phase normalizes its own output *before*
handing it to that unmodified, reused writer -- every row in a given
list ends up with the exact same key set (missing keys backfilled with
`None`), so any of the five writers behaves correctly regardless of which
generator produced which row.
"""

from __future__ import annotations

from typing import Any

from data_plane.subsetting.estate_io import RawEstate


def normalize_rows(rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Return a new list where every row dict has the same key set (the
    union of all keys across `rows`, missing values backfilled `None`),
    in first-seen key order. A no-op (returns `rows` unchanged) if `rows`
    is already homogeneous or empty."""

    if not rows:
        return rows

    all_keys: dict[str, None] = {}
    for row in rows:
        for key in row:
            all_keys[key] = None

    first_keys = set(rows[0].keys())
    if all(set(row.keys()) == first_keys for row in rows) and set(all_keys) == first_keys:
        return rows

    return [{key: row.get(key) for key in all_keys} for row in rows]


def normalize_estate_rows(estate: RawEstate) -> None:
    """Normalize every RawEstate entity's rows in place."""

    for field_name in (
        "member",
        "member_demographics",
        "address",
        "plan",
        "coverage",
        "provider",
        "diagnosis",
        "procedure",
        "claim_line",
        "pharmacy",
        "prescription",
        "encounter",
        "lab_result_ehr",
    ):
        setattr(estate, field_name, normalize_rows(getattr(estate, field_name)))

    for batch_name, rows in list(estate.claim.batches.items()):
        estate.claim.batches[batch_name] = normalize_rows(rows)


__all__ = ["normalize_estate_rows", "normalize_rows"]
