"""add resolution_notes to consumer_dataset_request

Revision ID: 0c097b0a72f8
Revises: edadf596e1ed
Create Date: 2026-09-26 06:04:48.933487

Phase 18B (resolves `docs/problems/problems_final_review.md` P3-4, "no REJECTED/
CANCELLED terminal state"): adds `resolution_notes`, populated by
`GovernanceRepository.reject_consumer_request`/`cancel_consumer_request`
to record who/why a `ConsumerDatasetRequest` was resolved to one of
those two new terminal `ConsumerRequestStatus` values.
`server_default=''` so this backfills cleanly against any row that
predates this migration. Generated with `alembic revision
--autogenerate` directly against `control_plane.db.models.Base.metadata`,
same discipline as the Phase 18A baseline migration and the Phase 18B
`scheduler_lock` migration.
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c097b0a72f8'
down_revision: Union[str, None] = 'edadf596e1ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consumer_dataset_request', sa.Column('resolution_notes', sa.Text(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consumer_dataset_request', 'resolution_notes')
    # ### end Alembic commands ###
