"""initial schema

Revision ID: 8387cacfabb1
Revises:
Create Date: 2026-09-25 20:55:03.241659

Phase 18A (resolves `problems_final_review.md` P1-3): this migration
was generated with `alembic revision --autogenerate` directly against
`control_plane.db.models.Base.metadata` -- the exact same schema
`init_schema`/`create_all` builds -- so it is a faithful, mechanically
verified baseline of every table this service has accumulated across
Phases 7, 10, and 11 (dataset lifecycle, governance, and platform
integrity/audit), not a hand-transcribed approximation. Running
`alembic upgrade head` against a fresh, empty database and then
`alembic check` produces "No new upgrade operations detected." -- i.e.
this migration and `Base.metadata` agree exactly (see
`services/control-plane/tests/test_migrations.py`).

Going forward, per `CONTRIBUTING.md`'s "every new behavior needs a
test" discipline applied to schema: any change to
`control_plane/db/models.py` gets a NEW migration
(`alembic revision --autogenerate -m "..."` from `services/control-plane/`,
then review the generated diff before committing it) -- never a hand
edit to this file, and never relying on `create_all` alone once a real
deployment has rows in its database. `create_all`/`init_schema` remain
in place for the from-scratch case (fresh test/dev SQLite files, which
have nothing to migrate from) -- see `control_plane.db.models`'s module
docstring.
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8387cacfabb1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_event',
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=512), nullable=False),
    sa.Column('outcome', sa.String(length=64), nullable=False),
    sa.Column('detail_json', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_audit_event_actor'), 'audit_event', ['actor'], unique=False)
    op.create_index(op.f('ix_audit_event_event_type'), 'audit_event', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_event_occurred_at'), 'audit_event', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_event_subject'), 'audit_event', ['subject'], unique=False)
    op.create_table('business_consumer',
    sa.Column('business_consumer_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('contact', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('business_consumer_id')
    )
    op.create_index(op.f('ix_business_consumer_code'), 'business_consumer', ['code'], unique=True)
    op.create_table('dataset_version',
    sa.Column('version_id', sa.String(length=36), nullable=False),
    sa.Column('dataset_name', sa.String(length=255), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('certification_report_id', sa.String(length=36), nullable=False),
    sa.Column('masking_policy_name', sa.String(length=255), nullable=False),
    sa.Column('masking_policy_version', sa.Integer(), nullable=False),
    sa.Column('masking_engine_version', sa.String(length=64), nullable=False),
    sa.Column('storage_uri', sa.String(length=1024), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('row_counts_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_reason', sa.String(length=1024), nullable=True),
    sa.Column('revoked_by', sa.String(length=255), nullable=True),
    sa.Column('rolled_back_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('version_id'),
    sa.UniqueConstraint('dataset_name', 'version_number', name='uq_dataset_version_number')
    )
    op.create_index(op.f('ix_dataset_version_dataset_name'), 'dataset_version', ['dataset_name'], unique=False)
    op.create_index(op.f('ix_dataset_version_status'), 'dataset_version', ['status'], unique=False)
    op.create_table('dead_letter_event',
    sa.Column('dead_letter_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('subject', sa.String(length=512), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('dead_letter_id')
    )
    op.create_index(op.f('ix_dead_letter_event_event_type'), 'dead_letter_event', ['event_type'], unique=False)
    op.create_index(op.f('ix_dead_letter_event_occurred_at'), 'dead_letter_event', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_dead_letter_event_subject'), 'dead_letter_event', ['subject'], unique=False)
    op.create_table('masking_policy_version',
    sa.Column('policy_version_id', sa.String(length=36), nullable=False),
    sa.Column('policy_name', sa.String(length=255), nullable=False),
    sa.Column('policy_version', sa.Integer(), nullable=False),
    sa.Column('masking_policy_json', sa.Text(), nullable=False),
    sa.Column('masking_engine_version', sa.String(length=64), nullable=False),
    sa.Column('approval_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('superseded_by_version_id', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('policy_version_id'),
    sa.UniqueConstraint('policy_name', 'policy_version', name='uq_masking_policy_version')
    )
    op.create_index(op.f('ix_masking_policy_version_approval_status'), 'masking_policy_version', ['approval_status'], unique=False)
    op.create_index(op.f('ix_masking_policy_version_policy_name'), 'masking_policy_version', ['policy_name'], unique=False)
    op.create_table('refresh_policy',
    sa.Column('policy_id', sa.String(length=36), nullable=False),
    sa.Column('policy_version', sa.Integer(), nullable=False),
    sa.Column('environment', sa.String(length=32), nullable=False),
    sa.Column('dataset_name', sa.String(length=255), nullable=True),
    sa.Column('cadence_type', sa.String(length=32), nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=True),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('grace_period_days', sa.Integer(), nullable=False),
    sa.Column('on_demand_allowed', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('policy_id')
    )
    op.create_index(op.f('ix_refresh_policy_dataset_name'), 'refresh_policy', ['dataset_name'], unique=False)
    op.create_index(op.f('ix_refresh_policy_environment'), 'refresh_policy', ['environment'], unique=False)
    op.create_table('environment_dataset_request',
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('environment', sa.String(length=32), nullable=False),
    sa.Column('dataset_name', sa.String(length=255), nullable=False),
    sa.Column('current_version_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('policy_id', sa.String(length=36), nullable=False),
    sa.Column('policy_version', sa.Integer(), nullable=False),
    sa.Column('consumer', sa.String(length=255), nullable=False),
    sa.Column('requested_by', sa.String(length=255), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('last_refresh_at', sa.DateTime(), nullable=True),
    sa.Column('next_refresh_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['current_version_id'], ['dataset_version.version_id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['refresh_policy.policy_id'], ),
    sa.PrimaryKeyConstraint('request_id'),
    sa.UniqueConstraint('environment', 'dataset_name', name='uq_environment_dataset')
    )
    op.create_index(op.f('ix_environment_dataset_request_dataset_name'), 'environment_dataset_request', ['dataset_name'], unique=False)
    op.create_index(op.f('ix_environment_dataset_request_environment'), 'environment_dataset_request', ['environment'], unique=False)
    op.create_table('policy_approval',
    sa.Column('approval_id', sa.String(length=36), nullable=False),
    sa.Column('policy_version_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('performed_by', sa.String(length=255), nullable=False),
    sa.Column('performed_at', sa.DateTime(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['policy_version_id'], ['masking_policy_version.policy_version_id'], ),
    sa.PrimaryKeyConstraint('approval_id')
    )
    op.create_index(op.f('ix_policy_approval_policy_version_id'), 'policy_approval', ['policy_version_id'], unique=False)
    op.create_table('consumer_dataset_request',
    sa.Column('consumer_request_id', sa.String(length=36), nullable=False),
    sa.Column('business_consumer_id', sa.String(length=36), nullable=False),
    sa.Column('business_consumer_code', sa.String(length=64), nullable=False),
    sa.Column('dataset_name', sa.String(length=255), nullable=False),
    sa.Column('environment', sa.String(length=32), nullable=False),
    sa.Column('policy_version_id', sa.String(length=36), nullable=False),
    sa.Column('masking_policy_name', sa.String(length=255), nullable=False),
    sa.Column('masking_policy_version', sa.Integer(), nullable=False),
    sa.Column('subset_size_hint', sa.String(length=512), nullable=False),
    sa.Column('refresh_cadence_type', sa.String(length=32), nullable=False),
    sa.Column('performance_requirements', sa.Text(), nullable=False),
    sa.Column('requested_by', sa.String(length=255), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('environment_request_id', sa.String(length=36), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['business_consumer_id'], ['business_consumer.business_consumer_id'], ),
    sa.ForeignKeyConstraint(['environment_request_id'], ['environment_dataset_request.request_id'], ),
    sa.ForeignKeyConstraint(['policy_version_id'], ['masking_policy_version.policy_version_id'], ),
    sa.PrimaryKeyConstraint('consumer_request_id')
    )
    op.create_index(op.f('ix_consumer_dataset_request_business_consumer_id'), 'consumer_dataset_request', ['business_consumer_id'], unique=False)
    op.create_index(op.f('ix_consumer_dataset_request_dataset_name'), 'consumer_dataset_request', ['dataset_name'], unique=False)
    op.create_index(op.f('ix_consumer_dataset_request_environment'), 'consumer_dataset_request', ['environment'], unique=False)
    op.create_table('refresh_run',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('environment', sa.String(length=32), nullable=False),
    sa.Column('dataset_name', sa.String(length=255), nullable=False),
    sa.Column('trigger', sa.String(length=16), nullable=False),
    sa.Column('triggered_by', sa.String(length=255), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('previous_version_id', sa.String(length=36), nullable=True),
    sa.Column('resulting_version_id', sa.String(length=36), nullable=True),
    sa.Column('succeeded', sa.Boolean(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['environment_dataset_request.request_id'], ),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('rollback_event',
    sa.Column('rollback_id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('environment', sa.String(length=32), nullable=False),
    sa.Column('dataset_name', sa.String(length=255), nullable=False),
    sa.Column('from_version_id', sa.String(length=36), nullable=False),
    sa.Column('to_version_id', sa.String(length=36), nullable=False),
    sa.Column('performed_by', sa.String(length=255), nullable=False),
    sa.Column('performed_at', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['environment_dataset_request.request_id'], ),
    sa.PrimaryKeyConstraint('rollback_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rollback_event')
    op.drop_table('refresh_run')
    op.drop_index(op.f('ix_consumer_dataset_request_environment'), table_name='consumer_dataset_request')
    op.drop_index(op.f('ix_consumer_dataset_request_dataset_name'), table_name='consumer_dataset_request')
    op.drop_index(op.f('ix_consumer_dataset_request_business_consumer_id'), table_name='consumer_dataset_request')
    op.drop_table('consumer_dataset_request')
    op.drop_index(op.f('ix_policy_approval_policy_version_id'), table_name='policy_approval')
    op.drop_table('policy_approval')
    op.drop_index(op.f('ix_environment_dataset_request_environment'), table_name='environment_dataset_request')
    op.drop_index(op.f('ix_environment_dataset_request_dataset_name'), table_name='environment_dataset_request')
    op.drop_table('environment_dataset_request')
    op.drop_index(op.f('ix_refresh_policy_environment'), table_name='refresh_policy')
    op.drop_index(op.f('ix_refresh_policy_dataset_name'), table_name='refresh_policy')
    op.drop_table('refresh_policy')
    op.drop_index(op.f('ix_masking_policy_version_policy_name'), table_name='masking_policy_version')
    op.drop_index(op.f('ix_masking_policy_version_approval_status'), table_name='masking_policy_version')
    op.drop_table('masking_policy_version')
    op.drop_index(op.f('ix_dead_letter_event_subject'), table_name='dead_letter_event')
    op.drop_index(op.f('ix_dead_letter_event_occurred_at'), table_name='dead_letter_event')
    op.drop_index(op.f('ix_dead_letter_event_event_type'), table_name='dead_letter_event')
    op.drop_table('dead_letter_event')
    op.drop_index(op.f('ix_dataset_version_status'), table_name='dataset_version')
    op.drop_index(op.f('ix_dataset_version_dataset_name'), table_name='dataset_version')
    op.drop_table('dataset_version')
    op.drop_index(op.f('ix_business_consumer_code'), table_name='business_consumer')
    op.drop_table('business_consumer')
    op.drop_index(op.f('ix_audit_event_subject'), table_name='audit_event')
    op.drop_index(op.f('ix_audit_event_occurred_at'), table_name='audit_event')
    op.drop_index(op.f('ix_audit_event_event_type'), table_name='audit_event')
    op.drop_index(op.f('ix_audit_event_actor'), table_name='audit_event')
    op.drop_table('audit_event')
    # ### end Alembic commands ###
