"""add illustrative capacity plan history table

Revision ID: 9f5e5af6718f
Revises: 0c097b0a72f8
Create Date: 2026-09-26 07:22:20.437074

Phase 18B (resolves `docs/problems/problems_final_review.md` P3-3, "illustrative
capacity scenarios are stateless; nothing can be saved/compared over
time"): adds `illustrative_capacity_plan`, the append-only table
`control_plane.domain.capacity.scenario_history.CapacityScenarioHistoryRepository`
uses to persist a saved, point-in-time `IllustrativeCapacityPlan`
snapshot as its full serialized JSON (`plan_json`) -- deliberately not
re-normalized into columns, since the shared `libs/contracts` shape is
already the one place that plan's fields are defined. Generated with
`alembic revision --autogenerate` directly against
`control_plane.db.models.Base.metadata`, same discipline as every other
Phase 18A/18B migration.
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f5e5af6718f'
down_revision: Union[str, None] = '0c097b0a72f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('illustrative_capacity_plan',
    sa.Column('saved_plan_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('plan_json', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('saved_plan_id')
    )
    op.create_index(op.f('ix_illustrative_capacity_plan_created_at'), 'illustrative_capacity_plan', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_illustrative_capacity_plan_created_at'), table_name='illustrative_capacity_plan')
    op.drop_table('illustrative_capacity_plan')
    # ### end Alembic commands ###
