"""add scheduler lock table

Revision ID: edadf596e1ed
Revises: 8387cacfabb1
Create Date: 2026-09-25 23:11:10.581752

Phase 18B (resolves `docs/problems/problems_final_review.md` P2-2, "no distributed
lock on concurrent scheduler sweeps"): adds `scheduler_lock`, the
row-per-lock mutual-exclusion table `control_plane.platform.scheduler_lock`
uses to serialize concurrent `POST /api/v1/lifecycle/scheduler/run-due`
calls. Generated with `alembic revision --autogenerate` directly
against `control_plane.db.models.Base.metadata`, same discipline as
the Phase 18A baseline migration.
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edadf596e1ed'
down_revision: Union[str, None] = '8387cacfabb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduler_lock',
    sa.Column('lock_name', sa.String(length=128), nullable=False),
    sa.Column('acquired_by', sa.String(length=255), nullable=False),
    sa.Column('acquired_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('lock_name')
    )
    op.create_index(op.f('ix_scheduler_lock_acquired_at'), 'scheduler_lock', ['acquired_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheduler_lock_acquired_at'), table_name='scheduler_lock')
    op.drop_table('scheduler_lock')
    # ### end Alembic commands ###
